# Generated by Django 2.2 on 2019-12-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddyapp', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trip_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tripmessages', to='travel_buddyapp.Trip'),
            preserve_default=False,
        ),
    ]
