# Generated by Django 2.2 on 2019-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddyapp', '0003_message_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messengers',
            field=models.ManyToManyField(related_name='mymessages', to='travel_buddyapp.User'),
        ),
    ]
