# Generated by Django 2.2 on 2019-12-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddyapp', '0004_message_messengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messengers',
        ),
    ]
